osx_image: xcode8.2
language: objective-c

cache:
  directories:
  - Carthage
  
before_install:
- brew update
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage bootstrap --platform iOS,Mac

script:
- set -o pipefail && xcodebuild -project Omnia.xcodeproj -scheme "Omnia-iOS" -sdk iphonesimulator clean build | xcpretty
- set -o pipefail && xcodebuild -project Omnia.xcodeproj -scheme "Omnia-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' -enableCodeCoverage YES test | xcpretty
- set -o pipefail && xcodebuild -project Omnia.xcodeproj -scheme "Omnia-Mac" -sdk macosx clean build | xcpretty
- set -o pipefail && xcodebuild -project Omnia.xcodeproj -scheme "Omnia-Mac" -sdk macosx -enableCodeCoverage YES test | xcpretty

notifications:
  email: false