osx_image: xcode9
language: objective-c

script:
- xcodebuild clean build -project Omnia.xcodeproj -scheme "Omnia-macOS" -sdk macosx
- xcodebuild test -project Omnia.xcodeproj -scheme "Omnia-macOS" -sdk macosx
- xcodebuild clean build -project Omnia.xcodeproj -scheme "Omnia-iOS" -sdk iphonesimulator
- xcodebuild test -project Omnia.xcodeproj -scheme "Omnia-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0.1'
- xcodebuild clean build -project Omnia.xcodeproj -scheme "Omnia-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0'
- xcodebuild test -project Omnia.xcodeproj -scheme "Omnia-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0'

notifications:
  email: false